In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_parquet("/Users/aniket/TU_Eindhoven/2_Study/Q4_2AMV10_Visual_Analytics/4_Code/2_AMV10_Visual_Analytics/data/movies_filtered_cleaned.parquet")
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34539 entries, 0 to 34538
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   movieId                34539 non-null  int64
 1   title                  34539 non-null  object
 2   original_language      34539 non-null  object
 3   release_date           34539 non-null  datetime64[ns]
 4   release_year           34539 non-null  float64
 5   release_month          34539 non-null  float64
 6   release_decade         34539 non-null  float64
 7   movie_age              34539 non-null  float64
 8   runtime                34539 non-null  float64
 9   poster_url             34539 non-null  object
 10  popularity             34539 non-null  object
 11  genre_list             34539 non-null  object
 12  main_genre             34539 non-null  object
 13  genre_count            34539 non-null  int64
 14  keywords               34539 non-null  object
 15  keyword_count          34539 non-null  int64
 16  tag_count              34539 non-null  int64
 17  director               34539 non-null  object
 18  lead_actor             34539 non-null  object
 19  vote_average           34539 non-null  float32
 20  vote_min               34539 non-null  float32
 21  vote_max               34539 non-null  float32
 22  vote_count             34539 non-null  int64
 23  popularity_score       34539 non-null  float64
 24  critical_success       34539 non-null  float64
 25  crowd_approval         34539 non-null  float64
 26  lead_actor_popularity  34539 non-null  float64
 27  director_popularity    34539 non-null  float64
dtypes: datetime64[ns](1), float32(3), float64(10), int64(5), object(9)
memory usage: 27.9 MB

In [3]:
df.describe()

,movieId,release_date,release_year,release_month,release_decade,movie_age,runtime,genre_count,keyword_count,tag_count,vote_average,vote_min,vote_max,vote_count,popularity_score,critical_success,crowd_approval,lead_actor_popularity,director_popularity
count,34539.000000,34539,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000,34539.000000
mean,87665.856452,1991-05-12 11:14:32.092417280,1990.862069,6.553345,1986.400301,34.137931,98.706419,2.583775,4.000000,11.619879,3.066322,1.298489,4.354324,787.137613,11.086130,7.076226,11.086130,0.262566,0.271994
min,1.000000,1901-01-01 00:00:00,1901.000000,1.000000,1900.000000,8.000000,10.000000,1.000000,0.000000,0.000000,0.500000,0.500000,0.500000,1.000000,0.346574,0.423287,0.346574,0.000000,0.000000
25%,27447.000000,1976-06-17 00:00:00,1976.000000,3.000000,1970.000000,15.000000,87.000000,2.000000,0.000000,2.000000,2.727273,0.500000,4.000000,4.000000,4.620981,3.796704,4.620981,0.175566,0.175757
50%,98041.000000,2000-01-28 00:00:00,2000.000000,7.000000,2000.000000,25.000000,95.000000,2.000000,3.000000,5.000000,3.152174,0.500000,5.000000,16.000000,8.627688,5.874281,8.627688,0.242879,0.247491
75%,137093.000000,2010-06-12 00:00:00,2010.000000,10.000000,2010.000000,49.000000,107.000000,3.000000,6.000000,13.000000,3.500000,2.000000,5.000000,147.000000,15.729454,9.477866,15.729454,0.333114,0.347726
max,191775.000000,2017-12-27 00:00:00,2017.000000,12.000000,2010.000000,124.000000,1256.000000,11.000000,97.000000,1032.000000,5.000000,5.000000,5.000000,97999.000000,50.845968,27.635078,50.845968,0.789434,0.827076
std,57996.139888,NaN,23.928861,3.572453,24.113052,23.928861,31.504898,1.347970,4.886961,19.725636,0.650625,1.059667,0.916308,3631.427661,8.369106,4.334376,8.369106,0.120682,0.130352

In [4]:
df.sample(6)

,movieId,title,original_language,release_date,release_year,release_month,release_decade,movie_age,runtime,poster_url,popularity,genre_list,main_genre,genre_count,keywords,keyword_count,tag_count,director,lead_actor,vote_average,vote_min,vote_max,vote_count,popularity_score,critical_success,crowd_approval,lead_actor_popularity,director_popularity
31657,164823,Do Not Resist,en,2016-04-30,2016.0,4.0,2010.0,9.0,70.0,https://image.tmdb.org/t/p/w500/9VObKGzYIfHn7c...,0.563982,[Documentary],Documentary,1,[],0,1,Craig Atkinson,James Comey,3.375000,3.0,4.0,8,7.415633,5.395316,7.415633,0.201649,0.210581
12691,70432,Fail Safe,en,2000-04-09,2000.0,4.0,2000.0,25.0,86.0,https://image.tmdb.org/t/p/w500/lKWVYudepN3Z3u...,1.583899,"[Drama, Thriller]",Drama,2,[],0,11,Stephen Frears,Walter Cronkite,3.584416,0.5,5.0,77,15.616255,9.600336,15.616255,0.290734,0.456515
24641,132307,Vagabond Lady,en,1935-05-03,1935.0,5.0,1930.0,90.0,71.0,https://image.tmdb.org/t/p/w500/wTYu1xBr7zC578...,0.10071,"[(no genres listed), Comedy, Drama, Romance]",Drama,4,"[boat, department store, brother, wedding, storm]",5,5,Sam Taylor,Robert Young,2.500000,2.5,2.5,1,1.732868,2.116434,1.732868,0.173414,0.163567
22474,122697,The Captain Hates the Sea,en,1934-11-02,1934.0,11.0,1930.0,91.0,93.0,https://image.tmdb.org/t/p/w500/ryJdjCYvwZAR8Q...,0.086883,[Comedy],Comedy,1,"[captain, three stooges, drinking]",3,3,Lewis Milestone,Victor McLaglen,2.500000,2.5,2.5,1,1.732868,2.116434,1.732868,0.182518,0.319977
9751,41425,The Dying Gaul,en,2005-01-01,2005.0,1.0,2000.0,20.0,95.0,https://image.tmdb.org/t/p/w500/gtWJWWDFrmrSRW...,0.978741,"[Drama, Romance]",Drama,2,[independent film],1,12,Craig Lucas,Patricia Clarkson,3.096774,0.5,5.0,62,12.830352,7.963563,12.830352,0.239137,0.291426
19402,108130,M for Mother,en,2006-10-24,2006.0,10.0,2000.0,19.0,113.0,https://image.tmdb.org/t/p/w500/gClYkEHCqGVZ0f...,0.041642,[Drama],Drama,1,[],0,1,Rasool Mollagholi Poor,Golshifteh Farahani,3.800000,3.0,5.0,5,6.808686,5.304343,6.808686,0.230479,0.213681

In [5]:
df.columns

Index(['movieId', 'title', 'original_language', 'release_date', 'release_year',
       'release_month', 'release_decade', 'movie_age', 'runtime', 'poster_url',
       'popularity', 'genre_list', 'main_genre', 'genre_count', 'keywords',
       'keyword_count', 'tag_count', 'director', 'lead_actor', 'vote_average',
       'vote_min', 'vote_max', 'vote_count', 'popularity_score',
       'critical_success', 'crowd_approval', 'lead_actor_popularity',
       'director_popularity'],
      dtype='object')