In [1]:
import pandas as pd

In [2]:
ratings_file_path = '/Users/aniket/.cache/kagglehub/datasets/grouplens/movielens-latest-full/versions/1/ratings.csv'
df_ratings = pd.read_csv(
    ratings_file_path,
    # header=None, # Indicate that there is no header row in the file
    dtype={'userId': 'int32', 'movieId': 'int32', 'rating': 'float32', 'timestamp': 'int64'}
    # If you don't need the timestamp initially, you could drop it here using usecols=['userId', 'movieId', 'rating']
)

In [3]:
df_movies = pd.read_parquet("/Users/aniket/TU_Eindhoven/2_Study/Q4_2AMV10_Visual_Analytics/4_Code/2_AMV10_Visual_Analytics/processed_data/movies_data_updated.parquet")

In [4]:
df_movies

,movieId,imdbId,tmdbId,imdb_id,title,original_language,overview,tagline,release_date,release_year,...,other_actors,spoken_language_names,main_language,has_translation,production_country_names,main_country,production_company_names,main_production_company,company_popularity,franchise_strength
0,1,114709,862,tt0114709,Toy Story,en,"Led by Woody, Andy's toys live happily in his ...",None,1995-10-30,1995.0,...,"[Tim Allen, Don Rickles, Jim Varney]",[English],English,[],[United States of America],United States of America,[Pixar Animation Studios],Pixar Animation Studios,0.177431,0.271092
1,2,113497,8844,tt0113497,Jumanji,en,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,1995-12-15,1995.0,...,"[Jonathan Hyde, Bradley Pierce, Bonnie Hunt]","[English, Francais]",English,[Francais],[United States of America],United States of America,"[TriStar Pictures, Teitler Film, Interscope Co...",TriStar Pictures,0.214557,NaN
2,3,113228,15602,tt0113228,Grumpier Old Men,en,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,1995-12-22,1995.0,...,"[Jack Lemmon, Sophia Loren, Daryl Hannah]",[English],English,[],[United States of America],United States of America,"[Warner Bros., Lancaster Gate]",Warner Bros.,0.421683,0.143885
3,4,114885,31357,tt0114885,Waiting to Exhale,en,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,1995-12-22,1995.0,...,"[Angela Bassett, Loretta Devine, Lela Rochon]",[English],English,[],[United States of America],United States of America,[Twentieth Century Fox Film Corporation],Twentieth Century Fox Film Corporation,0.604742,NaN
4,5,113041,11862,tt0113041,Father of the Bride Part II,en,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,1995-02-10,1995.0,...,"[Martin Short, Kimberly Williams-Paisley, Geor...",[English],English,[],[United States of America],United States of America,"[Sandollar Productions, Touchstone Pictures]",Sandollar Productions,0.118177,0.141060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46893,181393,1684935,79782,tt1684935,Venice,en,An atmospheric coming-of-age story featuring a...,None,2010-05-25,2010.0,...,"[Magdalena Cielecka, Mariusz Bonaszewski, Agni...",[Polski],Polski,[],[],None,[],None,NaN,NaN
46894,181751,169102,19666,tt0169102,Lagaan: Once Upon a Time in India,hi,Lagaan tells the tale of the Indian village Ch...,Once upon a time in India,2001-06-15,2001.0,...,"[Rachel Shelley, Paul Blackthorne, Kulbhushan ...","[English, hindii, rdw]",English,"[hindii, rdw]",[India],India,[Aamir Khan Productions],Aamir Khan Productions,0.173824,NaN
46895,183123,288243,97206,tt0288243,Taboo,en,Six young adults struggle with their personal ...,Would you ever...?,2002-01-14,2002.0,...,"[Eddie Kaye Thomas, Lori Heuring, Derek Hamilton]",[English],English,[],[Romania],Romania,"[Creative Entertainment Group, Silver Bullet P...",Creative Entertainment Group,0.084616,NaN
46896,187127,1691152,413765,tt1691152,David Lynch: The Art Life,en,An intimate journey through the formative year...,None,2017-02-15,2017.0,...,[],[English],English,[],[],None,[],None,NaN,NaN
46897,191775,211946,30508,tt0211946,Berlin Calling,de,A man tours clubs around the globe with his ma...,None,2008-10-01,2008.0,...,"[Rita Lengyel, Corinna Harfouch, Araba Walton]",[Deutsch],Deutsch,[],[Germany],Germany,[sabotage film GmbH],sabotage film GmbH,0.211499,NaN

In [5]:
movie_cols_to_merge = ['movieId', 'title', 'main_genre', 'director', 'lead_actor', 'release_year']
df_movies_subset = df_movies[movie_cols_to_merge]

In [6]:
df_ratings_with_details = pd.merge(
        df_ratings,
        df_movies_subset, # Merge with the subset of movie details
        on='movieId',
        how='inner' # Only keep ratings for movies that have details
    )
df_ratings_with_details

,userId,movieId,rating,timestamp,title,main_genre,director,lead_actor,release_year
0,1,307,3.5,1256677221,Three Colors: Blue,Drama,Krzysztof Kieślowski,Juliette Binoche,1993.0
1,1,481,3.5,1256677456,Kalifornia,Thriller,Dominic Sena,Brad Pitt,1993.0
2,1,1091,1.5,1256677471,Weekend at Bernie's,Comedy,Ted Kotcheff,Andrew McCarthy,1989.0
3,1,1257,4.5,1256677460,Better Off Dead...,Comedy,Savage Steve Holland,John Cusack,1985.0
4,1,1449,4.5,1256677264,Waiting for Guffman,Music,Christopher Guest,Christopher Guest,1996.0
...,...,...,...,...,...,...,...,...,...
27718138,283228,8542,4.5,1379882795,A Day at the Races,Comedy,Sam Wood,Groucho Marx,1937.0
27718139,283228,8712,4.5,1379882751,My Favorite Wife,Comedy,Garson Kanin,Cary Grant,1940.0
27718140,283228,34405,4.5,1379882889,Serenity,Science Fiction,Joss Whedon,Nathan Fillion,2005.0
27718141,283228,44761,4.5,1354159524,Brick,Drama,Rian Johnson,Joseph Gordon-Levitt,2005.0
27718142,283228,54286,4.5,1354159718,The Bourne Ultimatum,Action,Paul Greengrass,Matt Damon,2007.0

In [7]:
df_ratings_with_details["timestamp"] = pd.to_datetime(df_ratings_with_details["timestamp"], unit = "s")

In [8]:
df_ratings_with_details

,userId,movieId,rating,timestamp,title,main_genre,director,lead_actor,release_year
0,1,307,3.5,2009-10-27 21:00:21,Three Colors: Blue,Drama,Krzysztof Kieślowski,Juliette Binoche,1993.0
1,1,481,3.5,2009-10-27 21:04:16,Kalifornia,Thriller,Dominic Sena,Brad Pitt,1993.0
2,1,1091,1.5,2009-10-27 21:04:31,Weekend at Bernie's,Comedy,Ted Kotcheff,Andrew McCarthy,1989.0
3,1,1257,4.5,2009-10-27 21:04:20,Better Off Dead...,Comedy,Savage Steve Holland,John Cusack,1985.0
4,1,1449,4.5,2009-10-27 21:01:04,Waiting for Guffman,Music,Christopher Guest,Christopher Guest,1996.0
...,...,...,...,...,...,...,...,...,...
27718138,283228,8542,4.5,2013-09-22 20:46:35,A Day at the Races,Comedy,Sam Wood,Groucho Marx,1937.0
27718139,283228,8712,4.5,2013-09-22 20:45:51,My Favorite Wife,Comedy,Garson Kanin,Cary Grant,1940.0
27718140,283228,34405,4.5,2013-09-22 20:48:09,Serenity,Science Fiction,Joss Whedon,Nathan Fillion,2005.0
27718141,283228,44761,4.5,2012-11-29 03:25:24,Brick,Drama,Rian Johnson,Joseph Gordon-Levitt,2005.0
27718142,283228,54286,4.5,2012-11-29 03:28:38,The Bourne Ultimatum,Action,Paul Greengrass,Matt Damon,2007.0

In [12]:
df_ratings_with_details.loc[df_ratings_with_details["userId"]==4]

,userId,movieId,rating,timestamp,title,main_genre,director,lead_actor,release_year
42,4,1,4.0,2005-04-17 19:25:37,Toy Story,Animation,John Lasseter,Tom Hanks,1995.0
43,4,2,4.0,2005-04-17 19:48:26,Jumanji,Adventure,Joe Johnston,Robin Williams,1995.0
44,4,5,2.0,2005-08-14 03:34:13,Father of the Bride Part II,Comedy,Charles Shyer,Steve Martin,1995.0
45,4,6,4.5,2005-04-17 19:47:22,Heat,Action,Michael Mann,Al Pacino,1995.0
46,4,10,4.0,2005-04-17 19:26:35,GoldenEye,Adventure,Martin Campbell,Pierce Brosnan,1995.0
...,...,...,...,...,...,...,...,...,...
778,4,53972,3.5,2008-03-04 01:08:06,Live Free or Die Hard,Action,Len Wiseman,Bruce Willis,2007.0
779,4,53996,4.5,2008-03-04 01:08:29,Transformers,Adventure,Michael Bay,Shia LaBeouf,2007.0
780,4,54286,5.0,2008-03-04 01:06:15,The Bourne Ultimatum,Action,Paul Greengrass,Matt Damon,2007.0
781,4,55765,4.5,2008-03-04 01:07:20,American Gangster,Drama,Ridley Scott,Denzel Washington,2007.0
782,4,56367,4.5,2008-03-04 01:06:19,Juno,Comedy,Jason Reitman,Ellen Page,2007.0

In [13]:
df_ratings_with_details.to_parquet("../processed_data/ratings_data_extended.parquet", index = False)